In [1]:
import numpy as np
import pandas as pd

insurance_df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")

In [3]:
insurance_df.head(10)

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,F,Bachelor,825629.78%,62902.0,69.0,1/0/00,Personal Auto,Two-Door Car,159.383042
6,XZ87318,Oregon,F,College,538089.86%,55350.0,67.0,1/0/00,Corporate Auto,Four-Door Car,321.600000
7,CF85061,Arizona,M,Master,721610.03%,0.0,101.0,1/0/00,Corporate Auto,Four-Door Car,363.029680
8,DY87989,Oregon,M,Bachelor,2412750.40%,14072.0,71.0,1/0/00,Corporate Auto,Four-Door Car,511.200000
9,BQ94931,Oregon,F,College,738817.81%,28812.0,93.0,1/0/00,Special Auto,Four-Door Car,425.527834

In [5]:
insurance_clean_df = insurance_df.copy()

In [6]:
# Challenge 1
# Exercise 1 

insurance_clean_df.columns = [column_name.lower() for column_name in insurance_clean_df.columns]
insurance_clean_df.columns

Index(['customer', 'st', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'vehicle class', 'total claim amount'],
      dtype='object')

In [8]:
insurance_clean_df.columns = [column_name.replace(" ", "_") for column_name in insurance_clean_df.columns]
insurance_clean_df.columns

Index(['customer', 'st', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='object')

In [14]:
insurance_clean_df = insurance_clean_df.rename(columns={
    "st" : "state"
})

In [15]:
insurance_clean_df.columns

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='object')

In [23]:
insurance_clean_df.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [25]:
# Exercise 2

for column in insurance_clean_df.columns:
    print(insurance_clean_df[column].value_counts())
    print()

customer
RB50392    1
HJ15383    1
AO74776    1
HQ82233    1
OL72737    1
          ..
RO26085    1
ES57969    1
JK55587    1
RN97635    1
MY31220    1
Name: count, Length: 1071, dtype: int64

state
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64

gender
F         457
M         413
Male       39
female     28
Femal      17
Name: count, dtype: int64

education
Bachelor                324
College                 313
High School or Below    296
Master                   94
Doctor                   37
Bachelors                 7
Name: count, dtype: int64

customer_lifetime_value
445811.34%     4
251459.20%     4
272535.64%     3
578018.22%     3
684615.03%     3
              ..
245357.08%     1
507566.27%     1
321497.94%     1
1227534.31%    1
899704.02%     1
Name: count, Length: 1027, dtype: int64

income
0.0        252
43860.0      4
17622.0      4
36650.0      3
14072.0      3
          ...
29486.0      1
58557.0      1
25632.0      1
18768.0      1
54230.0      1
Name: count, Length: 774, dtype: int64

monthly_premium_auto
65.0     47
63.0     39
71.0     37
67.0     37
73.0     37
         ..
177.0     1
181.0     1
276.0     1
253.0     1
199.0     1
Name: count, Length: 132, dtype: int64

number_of_open_complaints
1/0/00    830
1/1/00    138
1/2/00     50
1/3/00     34
1/4/00     13
1/5/00      6
Name: count, dtype: int64

policy_type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

vehicle_class
Four-Door Car    576
Two-Door Car     205
SUV              199
Sports Car        57
Luxury SUV        20
Luxury Car        14
Name: count, dtype: int64

total_claim_amount
321.600000    19
331.200000    15
312.000000    14
350.400000    14
316.800000    12
              ..
421.484456     1
430.505942     1
7.646763       1
55.510526      1
207.320041     1
Name: count, Length: 761, dtype: int64

In [26]:
insurance_clean_df["gender"] = insurance_clean_df["gender"].replace({
    "Femal": "F",
    "female": "F",
    "Male": "M"
})

In [27]:
insurance_clean_df["gender"].value_counts()

gender
F    502
M    452
Name: count, dtype: int64

In [28]:
insurance_clean_df["state"] = insurance_clean_df["state"].replace({
    "Cali": "California",
    "WA": "Washington",
    "AZ": "Arizona"
})

In [29]:
insurance_clean_df["state"].value_counts()

state
California    331
Oregon        320
Arizona       211
Washington    111
Nevada         98
Name: count, dtype: int64

In [30]:
insurance_clean_df["education"] = insurance_clean_df["education"].replace({
    "Bachelors": "Bachelor"
})

In [31]:
insurance_clean_df["education"].value_counts()

education
Bachelor                331
College                 313
High School or Below    296
Master                   94
Doctor                   37
Name: count, dtype: int64

In [36]:
insurance_clean_df["customer_lifetime_value"] = insurance_clean_df["customer_lifetime_value"].str.replace("%", "")

In [37]:
insurance_clean_df["customer_lifetime_value"].head()

0           NaN
1     697953.59
2    1288743.17
3     764586.18
4     536307.65
Name: customer_lifetime_value, dtype: object

In [44]:
insurance_clean_df["vehicle_class"] = insurance_clean_df["vehicle_class"].replace({
    "Sports Car": "Luxury",
    "Luxury SUV": "Luxury",
    "Luxury Car": "Luxury"
})

In [45]:
insurance_clean_df["vehicle_class"].value_counts()

vehicle_class
Four-Door Car    576
Two-Door Car     205
SUV              199
Luxury            91
Name: count, dtype: int64

In [46]:
# Exercise 3

insurance_clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   object
 1   state                      1071 non-null   object
 2   gender                     954 non-null    object
 3   education                  1071 non-null   object
 4   customer_lifetime_value    1068 non-null   object
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   object
 8   policy_type                1071 non-null   object
 9   vehicle_class              1071 non-null   object
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB

In [47]:
insurance_clean_df["customer_lifetime_value"] = insurance_clean_df["customer_lifetime_value"].astype("float")

In [48]:
insurance_clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   object
 1   state                      1071 non-null   object
 2   gender                     954 non-null    object
 3   education                  1071 non-null   object
 4   customer_lifetime_value    1068 non-null   float64
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   object
 8   policy_type                1071 non-null   object
 9   vehicle_class              1071 non-null   object
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(4), object(7)
memory usage: 344.6+ KB

In [49]:
insurance_clean_df["number_of_open_complaints"].unique()

array(['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan],
      dtype=object)

In [50]:
insurance_clean_df["number_of_open_complaints"] = insurance_clean_df["number_of_open_complaints"].str.split("/").str[1].astype(float)

In [51]:
insurance_clean_df["number_of_open_complaints"].unique()

array([ 0.,  2.,  1.,  3.,  5.,  4., nan])

In [52]:
# Exercise 4

insurance_clean_df.isnull().head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,False,False,True,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False

In [56]:
insurance_clean_df.isnull().sum()

customer                     2937
state                        2937
gender                       3054
education                    2937
customer_lifetime_value      2940
income                       2937
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
dtype: int64

In [57]:
insurance_clean_df.shape

(4008, 11)

In [58]:
insurance_clean_df.dropna().shape

(952, 11)

In [59]:
insurance_clean_df = insurance_clean_df.dropna(how= "all")
insurance_clean_df.shape

(1071, 11)

In [60]:
insurance_clean_df.isnull().sum()

customer                       0
state                          0
gender                       117
education                      0
customer_lifetime_value        3
income                         0
monthly_premium_auto           0
number_of_open_complaints      0
policy_type                    0
vehicle_class                  0
total_claim_amount             0
dtype: int64

In [62]:
most_common_gender = insurance_clean_df["gender"].mode()[0]
print("Most common gender:", most_common_gender)

Most common gender: F

In [64]:
insurance_clean_df = insurance_clean_df.fillna({
    "gender": most_common_gender
})

In [65]:
insurance_clean_df.isnull().sum()

customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      3
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

In [66]:
# Exercise 5

insurance_clean_df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1066    False
1067    False
1068    False
1069    False
1070    False
Length: 1071, dtype: bool

In [67]:
insurance_clean_df.duplicated().sum()

np.int64(0)

In [68]:
insurance_df.duplicated().sum()

np.int64(2936)

In [70]:
# There are no duplicates found in insurance_clean_df dataframe.

In [71]:
insurance_clean_df.to_csv("insurance_cleaned.csv", index=False)