In [57]:
# CHALLENGE 1

import numpy as np
import pandas as pd

insurance_df = pd.read_csv("insurance_cleaned.csv")
insurance_df_2 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv")
insurance_df_3 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv")

In [58]:
insurance_df.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,F,Master,NaN,0.0,1000.0,0.0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,0.0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,0.0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,0.0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,0.0,Personal Auto,Four-Door Car,17.269323

In [59]:
insurance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1071 entries, 0 to 1070
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   object
 1   state                      1071 non-null   object
 2   gender                     1071 non-null   object
 3   education                  1071 non-null   object
 4   customer_lifetime_value    1068 non-null   float64
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   float64
 8   policy_type                1071 non-null   object
 9   vehicle_class              1071 non-null   object
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(5), object(6)
memory usage: 92.2+ KB

In [60]:
insurance_df_2.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Total Claim Amount,Policy Type,Vehicle Class
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,633.6,Personal Auto,Four-Door Car
1,CW49887,California,F,Master,462680.11%,79487,114,1/0/00,547.2,Special Auto,SUV
2,MY31220,California,F,College,899704.02%,54230,112,1/0/00,537.6,Personal Auto,Two-Door Car
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1/1/00,1027.2,Personal Auto,Luxury Car
4,WH52799,Arizona,F,College,380812.21%,94903,94,1/0/00,451.2,Corporate Auto,Two-Door Car

In [61]:
insurance_df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 996 entries, 0 to 995
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   996 non-null    object
 1   ST                         996 non-null    object
 2   GENDER                     991 non-null    object
 3   Education                  996 non-null    object
 4   Customer Lifetime Value    992 non-null    object
 5   Income                     996 non-null    int64
 6   Monthly Premium Auto       996 non-null    int64
 7   Number of Open Complaints  996 non-null    object
 8   Total Claim Amount         996 non-null    float64
 9   Policy Type                996 non-null    object
 10  Vehicle Class              996 non-null    object
dtypes: float64(1), int64(2), object(8)
memory usage: 85.7+ KB

In [62]:
insurance_df_3.head()

,Customer,State,Customer Lifetime Value,Education,Gender,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Total Claim Amount,Vehicle Class
0,SA25987,Washington,3479.137523,High School or Below,M,0,104,0,Personal Auto,499.200000,Two-Door Car
1,TB86706,Arizona,2502.637401,Master,M,0,66,0,Personal Auto,3.468912,Two-Door Car
2,ZL73902,Nevada,3265.156348,Bachelor,F,25820,82,0,Personal Auto,393.600000,Four-Door Car
3,KX23516,California,4455.843406,High School or Below,F,0,121,0,Personal Auto,699.615192,SUV
4,FN77294,California,7704.958480,High School or Below,M,30366,101,2,Personal Auto,484.800000,SUV

In [63]:
insurance_df_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7070 entries, 0 to 7069
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   7070 non-null   object
 1   State                      7070 non-null   object
 2   Customer Lifetime Value    7070 non-null   float64
 3   Education                  7070 non-null   object
 4   Gender                     7070 non-null   object
 5   Income                     7070 non-null   int64
 6   Monthly Premium Auto       7070 non-null   int64
 7   Number of Open Complaints  7070 non-null   int64
 8   Policy Type                7070 non-null   object
 9   Total Claim Amount         7070 non-null   float64
 10  Vehicle Class              7070 non-null   object
dtypes: float64(2), int64(3), object(6)
memory usage: 607.7+ KB

In [64]:
insurance_df_2.columns = [column_name.lower() for column_name in insurance_df_2.columns]
insurance_df_2.columns

Index(['customer', 'st', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'total claim amount', 'policy type', 'vehicle class'],
      dtype='object')

In [65]:
insurance_df_2.columns = [column_name.replace(" ", "_") for column_name in insurance_df_2.columns]
insurance_df_2.columns

Index(['customer', 'st', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'total_claim_amount', 'policy_type', 'vehicle_class'],
      dtype='object')

In [66]:
insurance_df_2 = insurance_df_2.rename(columns={
    "st" : "state"
})

In [67]:
insurance_df_2.columns

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'total_claim_amount', 'policy_type', 'vehicle_class'],
      dtype='object')

In [68]:
insurance_df_2["customer_lifetime_value"] = insurance_df_2["customer_lifetime_value"].str.replace("%", "")
insurance_df_2["customer_lifetime_value"].head()

0     323912.47
1     462680.11
2     899704.02
3    2580706.30
4     380812.21
Name: customer_lifetime_value, dtype: object

In [69]:
insurance_df_2["number_of_open_complaints"] = insurance_df_2["number_of_open_complaints"].str.split("/").str[1].astype(float)

In [70]:
insurance_df_2[["customer_lifetime_value", "income", "monthly_premium_auto", "number_of_open_complaints"]] = insurance_df_2[["customer_lifetime_value", "income", "monthly_premium_auto", "number_of_open_complaints"]].astype("float")

In [71]:
insurance_df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 996 entries, 0 to 995
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   996 non-null    object
 1   state                      996 non-null    object
 2   gender                     991 non-null    object
 3   education                  996 non-null    object
 4   customer_lifetime_value    992 non-null    float64
 5   income                     996 non-null    float64
 6   monthly_premium_auto       996 non-null    float64
 7   number_of_open_complaints  996 non-null    float64
 8   total_claim_amount         996 non-null    float64
 9   policy_type                996 non-null    object
 10  vehicle_class              996 non-null    object
dtypes: float64(5), object(6)
memory usage: 85.7+ KB

In [72]:
insurance_df_3.columns = [column_name.lower() for column_name in insurance_df_3.columns]
insurance_df_3 .columns

Index(['customer', 'state', 'customer lifetime value', 'education', 'gender',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'total claim amount', 'vehicle class'],
      dtype='object')

In [73]:
insurance_df_3.columns = [column_name.replace(" ", "_") for column_name in insurance_df_3.columns]
insurance_df_3.columns

Index(['customer', 'state', 'customer_lifetime_value', 'education', 'gender',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'total_claim_amount', 'vehicle_class'],
      dtype='object')

In [74]:
insurance_df_3 = insurance_df_3.rename(columns={
    "st" : "state"
})

In [75]:
insurance_df_3.columns

Index(['customer', 'state', 'customer_lifetime_value', 'education', 'gender',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'total_claim_amount', 'vehicle_class'],
      dtype='object')

In [76]:
insurance_df_3[["income", "monthly_premium_auto", "number_of_open_complaints"]] = insurance_df_3[["income", "monthly_premium_auto", "number_of_open_complaints"]].astype("float")

In [77]:
insurance_df_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7070 entries, 0 to 7069
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   7070 non-null   object
 1   state                      7070 non-null   object
 2   customer_lifetime_value    7070 non-null   float64
 3   education                  7070 non-null   object
 4   gender                     7070 non-null   object
 5   income                     7070 non-null   float64
 6   monthly_premium_auto       7070 non-null   float64
 7   number_of_open_complaints  7070 non-null   float64
 8   policy_type                7070 non-null   object
 9   total_claim_amount         7070 non-null   float64
 10  vehicle_class              7070 non-null   object
dtypes: float64(5), object(6)
memory usage: 607.7+ KB

In [78]:
print(insurance_df.columns.tolist())
print(insurance_df_2.columns.tolist())
print(insurance_df_3.columns.tolist())

['customer', 'state', 'gender', 'education', 'customer_lifetime_value', 'income', 'monthly_premium_auto', 'number_of_open_complaints', 'policy_type', 'vehicle_class', 'total_claim_amount']
['customer', 'state', 'gender', 'education', 'customer_lifetime_value', 'income', 'monthly_premium_auto', 'number_of_open_complaints', 'total_claim_amount', 'policy_type', 'vehicle_class']
['customer', 'state', 'customer_lifetime_value', 'education', 'gender', 'income', 'monthly_premium_auto', 'number_of_open_complaints', 'policy_type', 'total_claim_amount', 'vehicle_class']

In [79]:
combined_insurance_df = pd.concat([insurance_df, insurance_df_2, insurance_df_3], axis=0, ignore_index=True, join="outer")

In [80]:
combined_insurance_df.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,F,Master,NaN,0.0,1000.0,0.0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,0.0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,0.0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,0.0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,0.0,Personal Auto,Four-Door Car,17.269323

In [81]:
combined_insurance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9137 entries, 0 to 9136
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9137 non-null   object
 1   state                      9137 non-null   object
 2   gender                     9132 non-null   object
 3   education                  9137 non-null   object
 4   customer_lifetime_value    9130 non-null   float64
 5   income                     9137 non-null   float64
 6   monthly_premium_auto       9137 non-null   float64
 7   number_of_open_complaints  9137 non-null   float64
 8   policy_type                9137 non-null   object
 9   vehicle_class              9137 non-null   object
 10  total_claim_amount         9137 non-null   float64
dtypes: float64(5), object(6)
memory usage: 785.3+ KB

In [82]:
combined_insurance_df.shape

(9137, 11)

In [83]:
combined_insurance_df.isnull()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
9132,False,False,False,False,False,False,False,False,False,False,False
9133,False,False,False,False,False,False,False,False,False,False,False
9134,False,False,False,False,False,False,False,False,False,False,False
9135,False,False,False,False,False,False,False,False,False,False,False
9136,False,False,False,False,False,False,False,False,False,False,False

In [84]:
combined_insurance_df.isnull().sum()

customer                     0
state                        0
gender                       5
education                    0
customer_lifetime_value      7
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

In [85]:
combined_insurance_df[combined_insurance_df["customer_lifetime_value"].isnull()]

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,F,Master,NaN,0.0,1000.0,0.0,Personal Auto,Four-Door Car,2.704934
78,SP81997,Washington,F,Master,NaN,41275.0,96.0,0.0,Personal Auto,Four-Door Car,41.122303
988,GT62080,Washington,M,High School or Below,NaN,55561.0,63.0,0.0,Personal Auto,Four-Door Car,227.872071
1396,RI52095,Washington,M,High School or Below,NaN,51878.0,66.0,1.0,Personal Auto,Four-Door Car,316.800000
1443,HF88410,Washington,NaN,High School or Below,NaN,36765.0,66.0,1.0,Personal Auto,Four-Door Car,320.849072
1651,MW80236,Washington,M,Master,NaN,0.0,70.0,0.0,Personal Auto,Four-Door Car,336.000000
1932,TO60700,Washington,F,Bachelors,NaN,25859.0,74.0,0.0,Special Auto,Four-Door Car,355.200000

In [86]:
for column in combined_insurance_df.columns:
    print(combined_insurance_df[column].value_counts())
    print()

customer
QD28391    2
YB66933    2
LY14355    2
FX36546    2
OT85112    2
          ..
KG49115    1
NT78297    1
TN66124    1
JV99867    1
Y167826    1
Name: count, Length: 9056, dtype: int64

state
California    3152
Oregon        2601
Arizona       1655
Nevada         882
Washington     798
AZ              49
Name: count, dtype: int64

gender
F         4722
M         4407
female       2
Male         1
Name: count, dtype: int64

education
Bachelor                2726
College                 2682
High School or Below    2616
Master                   752
Doctor                   344
Bachelors                 17
Name: count, dtype: int64

customer_lifetime_value
16468.220790    6
5246.278375     6
22332.439460    6
4270.034394     6
5107.163002     6
               ..
7477.176362     1
15700.284360    1
2968.077571     1
5452.171237     1
2611.836866     1
Name: count, Length: 8211, dtype: int64

income
0.0        2294
95697.0      13
26876.0       8
61108.0       8
10621.0       8
           ...
26599.0       1
75774.0       1
85412.0       1
42968.0       1
21941.0       1
Name: count, Length: 5655, dtype: int64

monthly_premium_auto
65.0     351
66.0     312
71.0     304
73.0     303
63.0     290
        ...
178.0      1
204.0      1
281.0      1
275.0      1
286.0      1
Name: count, Length: 209, dtype: int64

number_of_open_complaints
0.0    7255
1.0    1012
2.0     376
3.0     290
4.0     148
5.0      56
Name: count, dtype: int64

policy_type
Personal Auto     6792
Corporate Auto    1965
Special Auto       380
Name: count, dtype: int64

vehicle_class
Four-Door Car    4641
Two-Door Car     1896
SUV              1774
Sports Car        426
Luxury SUV        162
Luxury Car        147
Luxury             91
Name: count, dtype: int64

total_claim_amount
316.800000    119
292.800000    111
312.000000    108
350.400000    107
321.600000    104
             ...
434.757900      1
389.636991      1
114.743547      1
733.737214      1
790.784983      1
Name: count, Length: 5070, dtype: int64

In [87]:
combined_insurance_df["gender"] = combined_insurance_df["gender"].replace({
    "female": "F",
    "Male": "M"
})

In [88]:
combined_insurance_df["state"] = combined_insurance_df["state"].replace({
    "AZ": "Arizona"
})

In [89]:
combined_insurance_df["education"] = combined_insurance_df["education"].replace({
    "Bachelors": "Bachelor"
})

In [90]:
combined_insurance_df["vehicle_class"] = combined_insurance_df["vehicle_class"].replace({
    "Sports Car": "Luxury",
    "Luxury SUV": "Luxury",
    "Luxury Car": "Luxury"
})

In [91]:
for column in combined_insurance_df.columns:
    print(combined_insurance_df[column].value_counts())
    print()

customer
QD28391    2
YB66933    2
LY14355    2
FX36546    2
OT85112    2
          ..
KG49115    1
NT78297    1
TN66124    1
JV99867    1
Y167826    1
Name: count, Length: 9056, dtype: int64

state
California    3152
Oregon        2601
Arizona       1704
Nevada         882
Washington     798
Name: count, dtype: int64

gender
F    4724
M    4408
Name: count, dtype: int64

education
Bachelor                2743
College                 2682
High School or Below    2616
Master                   752
Doctor                   344
Name: count, dtype: int64

customer_lifetime_value
16468.220790    6
5246.278375     6
22332.439460    6
4270.034394     6
5107.163002     6
               ..
7477.176362     1
15700.284360    1
2968.077571     1
5452.171237     1
2611.836866     1
Name: count, Length: 8211, dtype: int64

income
0.0        2294
95697.0      13
26876.0       8
61108.0       8
10621.0       8
           ...
26599.0       1
75774.0       1
85412.0       1
42968.0       1
21941.0       1
Name: count, Length: 5655, dtype: int64

monthly_premium_auto
65.0     351
66.0     312
71.0     304
73.0     303
63.0     290
        ...
178.0      1
204.0      1
281.0      1
275.0      1
286.0      1
Name: count, Length: 209, dtype: int64

number_of_open_complaints
0.0    7255
1.0    1012
2.0     376
3.0     290
4.0     148
5.0      56
Name: count, dtype: int64

policy_type
Personal Auto     6792
Corporate Auto    1965
Special Auto       380
Name: count, dtype: int64

vehicle_class
Four-Door Car    4641
Two-Door Car     1896
SUV              1774
Luxury            826
Name: count, dtype: int64

total_claim_amount
316.800000    119
292.800000    111
312.000000    108
350.400000    107
321.600000    104
             ...
434.757900      1
389.636991      1
114.743547      1
733.737214      1
790.784983      1
Name: count, Length: 5070, dtype: int64

In [92]:
combined_insurance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9137 entries, 0 to 9136
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9137 non-null   object
 1   state                      9137 non-null   object
 2   gender                     9132 non-null   object
 3   education                  9137 non-null   object
 4   customer_lifetime_value    9130 non-null   float64
 5   income                     9137 non-null   float64
 6   monthly_premium_auto       9137 non-null   float64
 7   number_of_open_complaints  9137 non-null   float64
 8   policy_type                9137 non-null   object
 9   vehicle_class              9137 non-null   object
 10  total_claim_amount         9137 non-null   float64
dtypes: float64(5), object(6)
memory usage: 785.3+ KB

In [93]:
combined_insurance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9137 entries, 0 to 9136
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9137 non-null   object
 1   state                      9137 non-null   object
 2   gender                     9132 non-null   object
 3   education                  9137 non-null   object
 4   customer_lifetime_value    9130 non-null   float64
 5   income                     9137 non-null   float64
 6   monthly_premium_auto       9137 non-null   float64
 7   number_of_open_complaints  9137 non-null   float64
 8   policy_type                9137 non-null   object
 9   vehicle_class              9137 non-null   object
 10  total_claim_amount         9137 non-null   float64
dtypes: float64(5), object(6)
memory usage: 785.3+ KB

In [94]:
combined_insurance_df.isnull().head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False

In [95]:
combined_insurance_df.isnull().sum()

customer                     0
state                        0
gender                       5
education                    0
customer_lifetime_value      7
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

In [96]:
combined_insurance_df[combined_insurance_df["customer_lifetime_value"].isnull()]

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,F,Master,NaN,0.0,1000.0,0.0,Personal Auto,Four-Door Car,2.704934
78,SP81997,Washington,F,Master,NaN,41275.0,96.0,0.0,Personal Auto,Four-Door Car,41.122303
988,GT62080,Washington,M,High School or Below,NaN,55561.0,63.0,0.0,Personal Auto,Four-Door Car,227.872071
1396,RI52095,Washington,M,High School or Below,NaN,51878.0,66.0,1.0,Personal Auto,Four-Door Car,316.800000
1443,HF88410,Washington,NaN,High School or Below,NaN,36765.0,66.0,1.0,Personal Auto,Four-Door Car,320.849072
1651,MW80236,Washington,M,Master,NaN,0.0,70.0,0.0,Personal Auto,Four-Door Car,336.000000
1932,TO60700,Washington,F,Bachelor,NaN,25859.0,74.0,0.0,Special Auto,Four-Door Car,355.200000

In [97]:
combined_insurance_df = combined_insurance_df.dropna(how= "any")
combined_insurance_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9126 entries, 1 to 9136
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9126 non-null   object
 1   state                      9126 non-null   object
 2   gender                     9126 non-null   object
 3   education                  9126 non-null   object
 4   customer_lifetime_value    9126 non-null   float64
 5   income                     9126 non-null   float64
 6   monthly_premium_auto       9126 non-null   float64
 7   number_of_open_complaints  9126 non-null   float64
 8   policy_type                9126 non-null   object
 9   vehicle_class              9126 non-null   object
 10  total_claim_amount         9126 non-null   float64
dtypes: float64(5), object(6)
memory usage: 855.6+ KB

In [98]:
combined_insurance_df.isnull().sum()

customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

In [99]:
combined_insurance_df.duplicated()

1       False
2       False
3       False
4       False
5       False
        ...
9132    False
9133    False
9134    False
9135    False
9136    False
Length: 9126, dtype: bool

In [100]:
combined_insurance_df.duplicated().sum()

np.int64(3)

In [101]:
combined_insurance_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9126 entries, 1 to 9136
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9126 non-null   object
 1   state                      9126 non-null   object
 2   gender                     9126 non-null   object
 3   education                  9126 non-null   object
 4   customer_lifetime_value    9126 non-null   float64
 5   income                     9126 non-null   float64
 6   monthly_premium_auto       9126 non-null   float64
 7   number_of_open_complaints  9126 non-null   float64
 8   policy_type                9126 non-null   object
 9   vehicle_class              9126 non-null   object
 10  total_claim_amount         9126 non-null   float64
dtypes: float64(5), object(6)
memory usage: 855.6+ KB

In [102]:
combined_insurance_df[combined_insurance_df.duplicated()]

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
1071,GS98873,Arizona,F,Bachelor,323912.47,16061.0,88.0,0.0,Personal Auto,Four-Door Car,633.6
1072,CW49887,California,F,Master,462680.11,79487.0,114.0,0.0,Special Auto,SUV,547.2
1073,MY31220,California,F,College,899704.02,54230.0,112.0,0.0,Personal Auto,Two-Door Car,537.6

In [103]:
combined_insurance_df[combined_insurance_df["customer"] == "GS98873"]

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
1068,GS98873,Arizona,F,Bachelor,323912.47,16061.0,88.0,0.0,Personal Auto,Four-Door Car,633.6
1071,GS98873,Arizona,F,Bachelor,323912.47,16061.0,88.0,0.0,Personal Auto,Four-Door Car,633.6

In [104]:
combined_insurance_df[combined_insurance_df["customer"] == "CW49887"]

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
1069,CW49887,California,F,Master,462680.11,79487.0,114.0,0.0,Special Auto,SUV,547.2
1072,CW49887,California,F,Master,462680.11,79487.0,114.0,0.0,Special Auto,SUV,547.2

In [105]:
combined_insurance_df = combined_insurance_df.drop_duplicates()

In [106]:
combined_insurance_df.duplicated().sum()

np.int64(0)

In [107]:
combined_insurance_df.isnull().sum()

customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

In [108]:
for column in combined_insurance_df.columns:
    print(combined_insurance_df[column].value_counts())
    print()

customer
QD28391    2
NW21079    2
HL33607    2
YP47665    2
GP39118    2
          ..
QM39493    1
DW62397    1
WC77067    1
KG49115    1
Y167826    1
Name: count, Length: 9049, dtype: int64

state
California    3150
Oregon        2601
Arizona       1703
Nevada         882
Washington     787
Name: count, dtype: int64

gender
F    4718
M    4405
Name: count, dtype: int64

education
Bachelor                2738
College                 2680
High School or Below    2613
Master                   748
Doctor                   344
Name: count, dtype: int64

customer_lifetime_value
5096.673223     6
13727.799720    6
4349.308750     6
16468.220790    6
4650.063763     6
               ..
9407.452895     1
7477.176362     1
15700.284360    1
2968.077571     1
2611.836866     1
Name: count, Length: 8207, dtype: int64

income
0.0        2292
95697.0      13
26876.0       8
61108.0       8
10621.0       8
           ...
85896.0       1
34847.0       1
26599.0       1
75774.0       1
21941.0       1
Name: count, Length: 5649, dtype: int64

monthly_premium_auto
65.0     351
66.0     310
71.0     304
73.0     303
67.0     289
        ...
178.0      1
204.0      1
281.0      1
275.0      1
286.0      1
Name: count, Length: 208, dtype: int64

number_of_open_complaints
0.0    7243
1.0    1010
2.0     376
3.0     290
4.0     148
5.0      56
Name: count, dtype: int64

policy_type
Personal Auto     6782
Corporate Auto    1964
Special Auto       377
Name: count, dtype: int64

vehicle_class
Four-Door Car    4630
Two-Door Car     1894
SUV              1773
Luxury            826
Name: count, dtype: int64

total_claim_amount
316.800000    118
292.800000    110
312.000000    108
350.400000    107
321.600000    104
             ...
129.151543      1
85.612463       1
434.757900      1
389.636991      1
790.784983      1
Name: count, Length: 5067, dtype: int64

In [123]:
# CHALLENGE 2

insurance_df_new = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv")
insurance_df_new.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1

In [124]:
insurance_df_new.columns

Index(['unnamed:_0', 'customer', 'state', 'customer_lifetime_value',
       'response', 'coverage', 'education', 'effective_to_date',
       'employmentstatus', 'gender', 'income', 'location_code',
       'marital_status', 'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'policy_type', 'policy', 'renew_offer_type',
       'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size',
       'vehicle_type', 'month'],
      dtype='object')

In [125]:
insurance_df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   unnamed:_0                     10910 non-null  int64
 1   customer                       10910 non-null  object
 2   state                          10910 non-null  object
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10910 non-null  object
 5   coverage                       10910 non-null  object
 6   education                      10910 non-null  object
 7   effective_to_date              10910 non-null  object
 8   employmentstatus               10910 non-null  object
 9   gender                         10910 non-null  object
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  object
 12  marital_status                 10910 non-null  object
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10910 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_of_open_complaints      10910 non-null  float64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  object
 19  policy                         10910 non-null  object
 20  renew_offer_type               10910 non-null  object
 21  sales_channel                  10910 non-null  object
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10910 non-null  object
 24  vehicle_size                   10910 non-null  object
 25  vehicle_type                   10910 non-null  object
 26  month                          10910 non-null  int64
dtypes: float64(4), int64(6), object(17)
memory usage: 2.2+ MB

In [126]:
insurance_df_new.duplicated().sum()

np.int64(0)

In [127]:
insurance_df_new.isnull().sum()

unnamed:_0                       0
customer                         0
state                            0
customer_lifetime_value          0
response                         0
coverage                         0
education                        0
effective_to_date                0
employmentstatus                 0
gender                           0
income                           0
location_code                    0
marital_status                   0
monthly_premium_auto             0
months_since_last_claim          0
months_since_policy_inception    0
number_of_open_complaints        0
number_of_policies               0
policy_type                      0
policy                           0
renew_offer_type                 0
sales_channel                    0
total_claim_amount               0
vehicle_class                    0
vehicle_size                     0
vehicle_type                     0
month                            0
dtype: int64

In [128]:
for column in insurance_df_new.columns:
    print(insurance_df_new[column].value_counts())
    print()

unnamed:_0
0        1
7276     1
7268     1
7269     1
7270     1
        ..
3638     1
3639     1
3640     1
3641     1
10909    1
Name: count, Length: 10910, dtype: int64

customer
ID89933    7
DQ50258    5
AM79057    5
FP86246    5
KE35335    4
          ..
VW27730    1
ZX64745    1
CK24264    1
IX18485    1
WA60547    1
Name: count, Length: 9134, dtype: int64

state
California    4183
Oregon        2909
Arizona       1937
Nevada         993
Washington     888
Name: count, dtype: int64

customer_lifetime_value
7507.455372     11
5504.139033     11
5181.620895     10
13727.799720    10
5332.462694     10
                ..
3467.323976      1
14140.558850     1
20018.204590     1
7432.299921      1
11971.977650     1
Name: count, Length: 8041, dtype: int64

response
No     9444
Yes    1466
Name: count, dtype: int64

coverage
Basic       6660
Extended    3265
Premium      985
Name: count, dtype: int64

education
Bachelor                3272
College                 3204
High School or Below    3146
Master                   887
Doctor                   401
Name: count, dtype: int64

effective_to_date
2011-01-10    239
2011-01-27    239
2011-01-31    224
2011-01-17    221
2011-02-14    221
2011-01-26    220
2011-01-03    216
2011-01-19    212
2011-02-27    205
2011-01-28    203
2011-02-26    202
2011-01-20    201
2011-01-21    199
2011-02-04    198
2011-02-07    197
2011-02-19    196
2011-02-03    195
2011-01-11    195
2011-01-05    193
2011-02-28    192
2011-02-22    191
2011-01-02    191
2011-02-18    186
2011-02-10    186
2011-02-11    184
2011-01-23    184
2011-02-12    183
2011-01-18    183
2011-02-25    183
2011-01-08    182
2011-01-29    182
2011-01-09    182
2011-02-05    181
2011-02-01    181
2011-02-02    181
2011-02-09    180
2011-01-14    180
2011-01-24    179
2011-02-21    178
2011-01-07    178
2011-02-23    176
2011-01-30    173
2011-01-15    172
2011-01-16    172
2011-01-13    171
2011-01-01    171
2011-02-06    171
2011-01-25    168
2011-02-13    168
2011-02-16    167
2011-02-24    162
2011-02-17    162
2011-01-06    161
2011-02-20    156
2011-02-15    155
2011-02-08    155
2011-01-22    148
2011-01-12    148
2011-01-04    131
Name: count, dtype: int64

employmentstatus
Employed         6789
Unemployed       2787
Medical Leave     504
Disabled          499
Retired           331
Name: count, dtype: int64

gender
F    5573
M    5337
Name: count, dtype: int64

income
0        2787
95697      15
60920      11
68931      10
11432      10
         ...
45310       1
88055       1
74606       1
88043       1
64195       1
Name: count, Length: 5694, dtype: int64

location_code
Suburban    6902
Rural       2116
Urban       1892
Name: count, dtype: int64

marital_status
Married     6319
Single      2958
Divorced    1633
Name: count, dtype: int64

monthly_premium_auto
65     419
66     371
71     368
73     363
63     345
      ...
163      1
178      1
287      1
228      1
203      1
Name: count, Length: 202, dtype: int64

months_since_last_claim
15.149071    633
3.000000     426
6.000000     394
1.000000     386
7.000000     378
4.000000     373
2.000000     368
5.000000     355
0.000000     354
10.000000    346
16.000000    333
11.000000    331
15.000000    323
13.000000    320
8.000000     315
12.000000    307
17.000000    299
14.000000    299
9.000000     277
19.000000    276
23.000000    276
25.000000    269
21.000000    267
18.000000    257
20.000000    254
22.000000    246
24.000000    237
29.000000    234
28.000000    227
31.000000    221
26.000000    211
27.000000    208
30.000000    201
34.000000    199
33.000000    198
35.000000    157
32.000000    155
Name: count, dtype: int64

months_since_policy_inception
59    168
61    151
50    151
10    138
3     136
     ...
16     81
96     80
82     71
98     64
97     59
Name: count, Length: 100, dtype: int64

number_of_open_complaints
0.000000    8160
1.000000    1145
0.384256     633
2.000000     414
3.000000     324
4.000000     166
5.000000      68
Name: count, dtype: int64

number_of_policies
1    3864
2    2748
3    1380
7     532
9     505
5     498
4     488
8     461
6     434
Name: count, dtype: int64

policy_type
Personal Auto     8128
Corporate Auto    2341
Special Auto       441
Name: count, dtype: int64

policy
Personal L3     4118
Personal L2     2537
Personal L1     1473
Corporate L3    1221
Corporate L2     688
Corporate L1     432
Special L2       193
Special L3       170
Special L1        78
Name: count, dtype: int64

renew_offer_type
Offer1    4483
Offer2    3490
Offer3    1732
Offer4    1205
Name: count, dtype: int64

sales_channel
Agent          4121
Branch         3022
Call Center    2141
Web            1626
Name: count, dtype: int64

total_claim_amount
316.800000    139
292.800000    136
312.000000    132
350.400000    129
331.200000    119
             ...
137.168874      1
487.345606      1
45.152521       1
402.749918      1
618.288849      1
Name: count, Length: 5106, dtype: int64

vehicle_class
Four-Door Car    5834
Two-Door Car     2118
SUV              2012
Sports Car        550
Luxury SUV        208
Luxury Car        188
Name: count, dtype: int64

vehicle_size
Medsize    7873
Small      1966
Large      1071
Name: count, dtype: int64

vehicle_type
A    10910
Name: count, dtype: int64

month
1    5818
2    5092
Name: count, dtype: int64

In [129]:
insurance_df_new = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv", parse_dates=["effective_to_date"])
insurance_df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   unnamed:_0                     10910 non-null  int64
 1   customer                       10910 non-null  object
 2   state                          10910 non-null  object
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10910 non-null  object
 5   coverage                       10910 non-null  object
 6   education                      10910 non-null  object
 7   effective_to_date              10910 non-null  datetime64[ns]
 8   employmentstatus               10910 non-null  object
 9   gender                         10910 non-null  object
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  object
 12  marital_status                 10910 non-null  object
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10910 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_of_open_complaints      10910 non-null  float64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  object
 19  policy                         10910 non-null  object
 20  renew_offer_type               10910 non-null  object
 21  sales_channel                  10910 non-null  object
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10910 non-null  object
 24  vehicle_size                   10910 non-null  object
 25  vehicle_type                   10910 non-null  object
 26  month                          10910 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(6), object(16)
memory usage: 2.2+ MB

In [130]:
insurance_df_new.columns.tolist()

['unnamed:_0',
 'customer',
 'state',
 'customer_lifetime_value',
 'response',
 'coverage',
 'education',
 'effective_to_date',
 'employmentstatus',
 'gender',
 'income',
 'location_code',
 'marital_status',
 'monthly_premium_auto',
 'months_since_last_claim',
 'months_since_policy_inception',
 'number_of_open_complaints',
 'number_of_policies',
 'policy_type',
 'policy',
 'renew_offer_type',
 'sales_channel',
 'total_claim_amount',
 'vehicle_class',
 'vehicle_size',
 'vehicle_type',
 'month']

In [131]:
insurance_df_new["sales_channel"].value_counts()

sales_channel
Agent          4121
Branch         3022
Call Center    2141
Web            1626
Name: count, dtype: int64

In [133]:
# 1- Creating the pivot table showing the total revenue for each sales channel (branch, call center, web, and mail).

sales_channel_pivot = insurance_df_new.pivot_table(
    values="total_claim_amount", 
    index="sales_channel",
    aggfunc="sum"
)

In [135]:
sales_channel_pivot = sales_channel_pivot.round(2)
sales_channel_pivot

               total_claim_amount
sales_channel
Agent                  1810226.82
Branch                 1301204.00
Call Center             926600.82
Web                     706600.04

In [136]:
# Agent brings the most revenue at $1.81M, followed by Branch at $1.30M. Call Center and Web bring significantly less. This suggests the company relies heavily on human-driven sales channels, with Web being the least effective.

In [142]:
# 2- Creating the pivot table that shows the average customer lifetime value per gender and education level. 

av_customer_lifetime_value = insurance_df_new.pivot_table(
    values="customer_lifetime_value", 
    index="gender",
    columns="education",
    aggfunc="mean"
)

av_customer_lifetime_value

education,Bachelor,College,Doctor,High School or Below,Master
gender,,,,,
F,7874.269478,7748.823325,7328.508916,8675.220201,8157.053154
M,7703.601675,8052.459288,7415.333638,8149.687783,8168.832659

In [143]:
av_customer_lifetime_value = av_customer_lifetime_value.round(2)
av_customer_lifetime_value

education  Bachelor  College   Doctor  High School or Below   Master
gender
F           7874.27  7748.82  7328.51               8675.22  8157.05
M           7703.60  8052.46  7415.33               8149.69  8168.83

In [144]:
#Males with College education have the highest average CLV at $8,052.
#Females with High School or Below have the highest CLV among females at $8,675.
#Doctor level education has the lowest CLV for both genders.
#Overall CLV values are fairly similar across genders and education levels — no dramatic differences.