In [1]:
import numpy as np
import pandas as pd

In [2]:
insurance_df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")

In [3]:
# Challenge 1

insurance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   object
 1   ST                         1071 non-null   object
 2   GENDER                     954 non-null    object
 3   Education                  1071 non-null   object
 4   Customer Lifetime Value    1068 non-null   object
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   object
 8   Policy Type                1071 non-null   object
 9   Vehicle Class              1071 non-null   object
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB

In [4]:
insurance_df.shape

(4008, 11)

In [5]:
insurance_df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [6]:
insurance_clean_df = insurance_df.copy()
insurance_clean_df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [7]:
insurance_clean_df.columns

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='object')

In [8]:
insurance_clean_df = insurance_clean_df.rename(columns={
    "Customer": "customer",
    "ST": "st",
    "GENDER": "gender",
    "Education": "education",
    "Customer Lifetime Value": "clv",
    "Income": "income",
    "Monthly Premium Auto": "mpa",
    "Number of Open Complaints": "noc",
    "Policy Type": "pt",
    "Vehicle Class": "vc",
    "Total Claim Amount": "tca"
})

insurance_clean_df.columns

Index(['customer', 'st', 'gender', 'education', 'clv', 'income', 'mpa', 'noc',
       'pt', 'vc', 'tca'],
      dtype='object')

In [9]:
insurance_clean_df["clv"] = insurance_clean_df["clv"].str.replace("%", "")

In [11]:
# It looks like the data type for CLV and Number of Open Complaints are wrong. CLV should have been float and Number of Open Complaints have been integer.

insurance_clean_df["clv"] = insurance_clean_df["clv"].astype("float")
print(insurance_clean_df["clv"].dtypes)

float64

In [12]:
insurance_clean_df["noc"].unique()

array(['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan],
      dtype=object)

In [13]:
insurance_clean_df["noc"] = insurance_clean_df["noc"].str.split("/").str[1]

In [14]:
insurance_clean_df["noc"] = insurance_clean_df["noc"].astype("float")
print(insurance_clean_df["noc"].dtypes)

float64

In [15]:
insurance_clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   customer   1071 non-null   object
 1   st         1071 non-null   object
 2   gender     954 non-null    object
 3   education  1071 non-null   object
 4   clv        1068 non-null   float64
 5   income     1071 non-null   float64
 6   mpa        1071 non-null   float64
 7   noc        1071 non-null   float64
 8   pt         1071 non-null   object
 9   vc         1071 non-null   object
 10  tca        1071 non-null   float64
dtypes: float64(5), object(6)
memory usage: 344.6+ KB

In [16]:
insurance_clean_df.nunique()

customer     1071
st              8
gender          5
education       6
clv          1027
income        774
mpa           132
noc             6
pt              3
vc              6
tca           761
dtype: int64

In [17]:
insurance_clean_df["noc"]

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
4003    NaN
4004    NaN
4005    NaN
4006    NaN
4007    NaN
Name: noc, Length: 4008, dtype: float64

In [18]:
insurance_clean_df["noc"].unique()

array([ 0.,  2.,  1.,  3.,  5.,  4., nan])

In [19]:
insurance_clean_df.nunique()

customer     1071
st              8
gender          5
education       6
clv          1027
income        774
mpa           132
noc             6
pt              3
vc              6
tca           761
dtype: int64

In [20]:
# st, gender, education, noc, pt and vc are categorical values and rest are numerical.

In [21]:
insurance_clean_df[["st", "gender", "education", "noc", "pt", "vc"]].value_counts()

st          gender  education             noc  pt              vc
Oregon      F       High School or Below  0.0  Personal Auto   Four-Door Car    15
Arizona     F       High School or Below  0.0  Personal Auto   Four-Door Car    13
Oregon      F       College               0.0  Personal Auto   Four-Door Car    12
California  M       College               0.0  Personal Auto   Four-Door Car    11
Cali        M       Bachelor              0.0  Personal Auto   Four-Door Car    11
                                                                                ..
California  M       Bachelor              1.0  Corporate Auto  Four-Door Car     1
                                          0.0  Personal Auto   SUV               1
            Femal   Bachelor              0.0  Personal Auto   Four-Door Car     1
            F       Master                1.0  Special Auto    Two-Door Car      1
Washington  female  Master                0.0  Personal Auto   Two-Door Car      1
Name: count, Length: 544, dtype: int64

In [24]:
# Looks like the data needs to be cleaned up. gender has inconsistent values — F, Femal, female should all be the same thing, and M should be consistent too. st has duplicates for the same state — Cali and California represent the same place.

In [25]:
insurance_clean_df.describe()

                clv        income           mpa          noc          tca
count  1.068000e+03   1071.000000   1071.000000  1071.000000  1071.000000
mean   7.936903e+05  39295.701214    193.234360     0.394024   404.986909
std    6.434784e+05  30469.427060   1601.190369     0.883769   293.027260
min    2.004351e+05      0.000000     61.000000     0.000000     0.382107
25%    4.034080e+05  14072.000000     68.000000     0.000000   202.157702
50%    5.881742e+05  36234.000000     83.000000     0.000000   354.729129
75%    8.962872e+05  64631.000000    109.500000     0.000000   532.800000
max    5.816655e+06  99960.000000  35354.000000     5.000000  2893.239678

In [26]:
# For numeric columns, it seems like in clv and mpa there are big difference between mean and max value. This indicates high value outliers pulling the numbers up.

In [28]:
# Challange 2
# Exercise 1

insurance_clean_df.head()

,customer,st,gender,education,clv,income,mpa,noc,pt,vc,tca
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,0.0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,0.0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,0.0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,0.0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,0.0,Personal Auto,Four-Door Car,17.269323

In [30]:
insurance_clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   customer   1071 non-null   object
 1   st         1071 non-null   object
 2   gender     954 non-null    object
 3   education  1071 non-null   object
 4   clv        1068 non-null   float64
 5   income     1071 non-null   float64
 6   mpa        1071 non-null   float64
 7   noc        1071 non-null   float64
 8   pt         1071 non-null   object
 9   vc         1071 non-null   object
 10  tca        1071 non-null   float64
dtypes: float64(5), object(6)
memory usage: 344.6+ KB

In [31]:
insurance_clean_df.isnull().sum()

customer     2937
st           2937
gender       3054
education    2937
clv          2940
income       2937
mpa          2937
noc          2937
pt           2937
vc           2937
tca          2937
dtype: int64

In [32]:
insurance_clean_df.isnull()

,customer,st,gender,education,clv,income,mpa,noc,pt,vc,tca
0,False,False,True,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
4003,True,True,True,True,True,True,True,True,True,True,True
4004,True,True,True,True,True,True,True,True,True,True,True
4005,True,True,True,True,True,True,True,True,True,True,True
4006,True,True,True,True,True,True,True,True,True,True,True
4007,True,True,True,True,True,True,True,True,True,True,True

In [34]:
insurance_clean_df["st"]

0       Washington
1          Arizona
2           Nevada
3       California
4       Washington
           ...
4003           NaN
4004           NaN
4005           NaN
4006           NaN
4007           NaN
Name: st, Length: 4008, dtype: object

In [35]:
insurance_clean_df["st"].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali',
       'AZ', 'WA', nan], dtype=object)

In [36]:
insurance_clean_df["st"].value_counts()

st
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64

In [39]:
insurance_clean_df["st"].value_counts(ascending=True)

st
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Arizona       186
California    211
Oregon        320
Name: count, dtype: int64

In [40]:
insurance_clean_df["st"].value_counts(ascending=True).head(5)

st
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Name: count, dtype: int64

In [41]:
# Exercise 2

insurance_clean_df["pt"].value_counts()

pt
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

In [43]:
policy_counts = insurance_clean_df["pt"].value_counts()
policy_counts.idxmax()

'Personal Auto'

In [44]:
# Exercise 3

insurance_clean_df["pt"].value_counts()

pt
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

In [45]:
insurance_clean_df.head()

,customer,st,gender,education,clv,income,mpa,noc,pt,vc,tca
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,0.0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,0.0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,0.0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,0.0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,0.0,Personal Auto,Four-Door Car,17.269323

In [49]:
personal_auto_df = insurance_clean_df.loc[insurance_clean_df["pt"] == "Personal Auto"]
personal_auto_df

,customer,st,gender,education,clv,income,mpa,noc,pt,vc,tca
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,0.0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,0.0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,0.0,Personal Auto,Two-Door Car,566.472247
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,0.0,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,F,Bachelor,825629.78,62902.0,69.0,0.0,Personal Auto,Two-Door Car,159.383042
...,...,...,...,...,...,...,...,...,...,...,...
1065,XD85577,Cali,M,Bachelor,284226.69,69417.0,73.0,1.0,Personal Auto,Four-Door Car,30.874869
1066,TM65736,Oregon,M,Master,305955.03,38644.0,78.0,1.0,Personal Auto,Four-Door Car,361.455219
1067,VJ51327,Cali,F,High School or Below,2031499.76,63209.0,102.0,2.0,Personal Auto,SUV,207.320041
1068,GS98873,Arizona,F,Bachelor,323912.47,16061.0,88.0,0.0,Personal Auto,Four-Door Car,633.600000
1070,MY31220,California,F,College,899704.02,54230.0,112.0,0.0,Personal Auto,Two-Door Car,537.600000

In [50]:
corporate_auto_df = insurance_clean_df.loc[insurance_clean_df["pt"] == "Corporate Auto"]
corporate_auto_df

,customer,st,gender,education,clv,income,mpa,noc,pt,vc,tca
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,0.0,Corporate Auto,SUV,529.881344
6,XZ87318,Oregon,F,College,538089.86,55350.0,67.0,0.0,Corporate Auto,Four-Door Car,321.600000
7,CF85061,Arizona,M,Master,721610.03,0.0,101.0,0.0,Corporate Auto,Four-Door Car,363.029680
8,DY87989,Oregon,M,Bachelor,2412750.40,14072.0,71.0,0.0,Corporate Auto,Four-Door Car,511.200000
12,DP39365,California,NaN,Master,879879.70,77026.0,110.0,2.0,Corporate Auto,Four-Door Car,472.029737
...,...,...,...,...,...,...,...,...,...,...,...
1045,WZ31900,Oregon,F,Bachelor,864970.06,94389.0,107.0,0.0,Corporate Auto,SUV,85.063708
1050,BJ53923,Arizona,M,High School or Below,260027.21,51978.0,66.0,0.0,Corporate Auto,Four-Door Car,144.782152
1052,FB23788,Oregon,M,High School or Below,882883.50,86721.0,111.0,0.0,Corporate Auto,SUV,532.800000
1056,PI47776,Oregon,F,Bachelor,253070.51,89451.0,63.0,0.0,Corporate Auto,Four-Door Car,61.769564
1059,YG44474,Oregon,M,College,1401472.13,54193.0,117.0,0.0,Corporate Auto,SUV,720.752945

In [56]:
personal_auto_df.describe()

                clv        income           mpa         noc          tca
count  7.770000e+02    780.000000    780.000000  780.000000   780.000000
mean   8.029599e+05  38180.698718    185.701282    0.389744   404.820615
std    6.493341e+05  29952.165621   1389.378065    0.874337   286.640319
min    2.004351e+05      0.000000     61.000000    0.000000     0.382107
25%    4.165167e+05  12096.000000     68.000000    0.000000   213.016744
50%    5.928748e+05  35211.500000     82.000000    0.000000   350.626994
75%    9.095745e+05  62774.000000    109.000000    0.000000   529.200000
max    5.816655e+06  99790.000000  35354.000000    5.000000  2893.239678

In [52]:
corporate_auto_df.describe()

                clv        income           mpa         noc          tca
count  2.340000e+02    234.000000    234.000000  234.000000   234.000000
mean   7.674441e+05  41390.311966    243.683761    0.388889   415.606539
std    5.958606e+05  31708.868459   2305.259851    0.887711   312.682978
min    2.163870e+05      0.000000     61.000000    0.000000     5.395300
25%    3.854418e+05  16325.500000     68.000000    0.000000   203.506316
50%    5.553663e+05  39155.500000     85.000000    0.000000   376.720392
75%    8.672221e+05  69843.000000    110.000000    0.000000   537.600000
max    3.605754e+06  99960.000000  35353.000000    5.000000  2345.413441

In [62]:
personal_auto_mean = personal_auto_df["income"].mean()
corporate_auto_mean = corporate_auto_df["income"].mean()

print(f"Average income for Personal Auto is", personal_auto_mean)
print(f"Average income for Corporate Auto is", corporate_auto_mean)

Average income for Personal Auto is 38180.69871794872
Average income for Corporate Auto is 41390.31196581197